### ISSUE TITLE
Reading cif file does not work if the last line contains an atom

### ISSUE THREAD

**Issue by yakutovicha** [mharanczyk/zeoplusplus#5]
**network** program is hanging at the file reading stage if the last line of the cif file is not an empty one. 

In my opinion this issue should be resolved as it is not so clear for an inexperienced person where to look for the origin of the problem.

**Comment by ltalirz** [comment]
closing, this will be tracked in https://github.com/lsmo-epfl/zeopp-lsmo/issues/10 and https://github.com/ltalirz/aiida-zeopp/issues/62
